/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cinepolis;

import javax.swing.ImageIcon;

public class Menu extends javax.swing.JFrame {
    
    RegistrarReservacion registrarR = new RegistrarReservacion();
    RegistrarPelicula registrarP = new RegistrarPelicula();
    ModificarReservacion modificarR = new ModificarReservacion();
    ModificarPelicula modificarP = new ModificarPelicula();
    EliminarReservacion eliminarR = new EliminarReservacion();
    EliminarPelicula eliminarP = new EliminarPelicula();
    Consultar consultarM = new Consultar();
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        setIconImage(new ImageIcon(getClass().getResource("/cinepolis/cinepolisLogo.png")).getImage());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        registrar = new javax.swing.JMenu();
        peliculaR = new javax.swing.JMenuItem();
        reservacionR = new javax.swing.JMenuItem();
        modificar = new javax.swing.JMenu();
        peliculaM = new javax.swing.JMenuItem();
        reservacionM = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JMenu();
        peliculaE = new javax.swing.JMenuItem();
        reservacionE = new javax.swing.JMenuItem();
        consultar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CINEPOLIS");
        setLocation(new java.awt.Point(400, 90));

        principal.setBackground(new java.awt.Color(255, 255, 255));

        imagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinepolis/cinepolis.png"))); // NOI18N

        javax.swing.GroupLayout principalLayout = new javax.swing.GroupLayout(principal);
        principal.setLayout(principalLayout);
        principalLayout.setHorizontalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
        );
        principalLayout.setVerticalGroup(
            principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        registrar.setText("Registrar");

        peliculaR.setText("Pelicula");
        peliculaR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                peliculaRMouseReleased(evt);
            }
        });
        registrar.add(peliculaR);

        reservacionR.setText("Reservacion");
        reservacionR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                reservacionRMouseReleased(evt);
            }
        });
        registrar.add(reservacionR);

        jMenuBar2.add(registrar);

        modificar.setText("Modificar");

        peliculaM.setText("Pelicula");
        peliculaM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                peliculaMMouseReleased(evt);
            }
        });
        modificar.add(peliculaM);

        reservacionM.setText("Reservacion");
        reservacionM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                reservacionMMouseReleased(evt);
            }
        });
        modificar.add(reservacionM);

        jMenuBar2.add(modificar);

        eliminar.setText("Eliminar");

        peliculaE.setText("Pelicula");
        peliculaE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                peliculaEMouseReleased(evt);
            }
        });
        eliminar.add(peliculaE);

        reservacionE.setText("Reservacion");
        reservacionE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                reservacionEMouseReleased(evt);
            }
        });
        eliminar.add(reservacionE);

        jMenuBar2.add(eliminar);

        consultar.setText("Consultar");
        consultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarMouseClicked(evt);
            }
        });
        jMenuBar2.add(consultar);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reservacionRMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservacionRMouseReleased
        // TODO add your handling code here:
        registrarR.setVisible(true);
        registrarR.peliculas();
    }//GEN-LAST:event_reservacionRMouseReleased

    private void peliculaRMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peliculaRMouseReleased
        // TODO add your handling code here:
        registrarP.setVisible(true);
    }//GEN-LAST:event_peliculaRMouseReleased

    private void reservacionMMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservacionMMouseReleased
        // TODO add your handling code here:
        modificarR.setVisible(true);
    }//GEN-LAST:event_reservacionMMouseReleased

    private void peliculaMMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peliculaMMouseReleased
        // TODO add your handling code here:
        modificarP.setVisible(true);
    }//GEN-LAST:event_peliculaMMouseReleased

    private void peliculaEMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peliculaEMouseReleased
        // TODO add your handling code here:
        eliminarP.setVisible(true);
    }//GEN-LAST:event_peliculaEMouseReleased

    private void reservacionEMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservacionEMouseReleased
        // TODO add your handling code here:
        eliminarR.setVisible(true);
    }//GEN-LAST:event_reservacionEMouseReleased

    private void consultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarMouseClicked
        // TODO add your handling code here:
        consultarM.setVisible(true);
        consultarM.peliculas();
        consultarM.reservas();
    }//GEN-LAST:event_consultarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu consultar;
    private javax.swing.JMenu eliminar;
    private javax.swing.JLabel imagen;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu modificar;
    private javax.swing.JMenuItem peliculaE;
    private javax.swing.JMenuItem peliculaM;
    private javax.swing.JMenuItem peliculaR;
    private javax.swing.JPanel principal;
    private javax.swing.JMenu registrar;
    private javax.swing.JMenuItem reservacionE;
    private javax.swing.JMenuItem reservacionM;
    private javax.swing.JMenuItem reservacionR;
    // End of variables declaration//GEN-END:variables
}
